blank_issues_enabled: true
contact_links:
  - name: Add new ToDo
    about: made by config.yml
    url: https://github.com/dev-fjk/MyTodo/issues/new?template=custom.md&projects=dev-fjk%2FToDo%2F1&labels=ToDo
